# Generated by Django 4.2.7 on 2023-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discos", "0002_alter_categoria_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="imagen",
            field=models.ImageField(
                default="categorias/album_default.png",
                null=True,
                upload_to="categorias",
            ),
        ),
    ]
